# Dockerfile for building a Python application with Poetry and Reflex
# using Alpine Linux as the base image.
# This Dockerfile is designed to create a lightweight and efficient container
# for running Python applications with Poetry for dependency management
# and Reflex for live reloading during development.
# Use a multi-stage build to keep the final image size small
# Use the latest Alpine-based Python image
FROM python:3.12.11-alpine AS alpine-base
RUN apk update && apk upgrade --no-cache
RUN apk add --no-cache curl build-base linux-headers bash

# Install Reflex for live reloading
FROM alpine-base AS poetry-base
ENV POETRY_HOME=/opt/poetry
ENV POETRY_VENV=/opt/poetry-venv
ENV POETRY_CACHE_DIR=/opt/.cache
RUN curl -sSL https://install.python-poetry.org | python -
ENV PATH="$POETRY_HOME/bin:$POETRY_VENV/bin:/app/.venv/bin:$PATH"
RUN poetry config virtualenvs.create true \
    && poetry config virtualenvs.in-project true \
    && poetry config cache-dir $POETRY_CACHE_DIR \
    && poetry config installer.parallel true \
    && poetry config installer.max-workers 4 

WORKDIR /app
COPY poetry.lock pyproject.toml ./
RUN poetry install --no-root --only main

# Final stage: copy the application code and set the entrypoint
# Use the poetry-base stage to ensure all dependencies are installed
FROM poetry-base AS python-app
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY . .
ENTRYPOINT ["reflex", "run", "--env", "prod", "--backend-only", "--loglevel", "info" ]