"""teste

Revision ID: e83cc9d357f8
Revises: b57e0e969ab3
Create Date: 2025-05-06 18:50:52.004201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83cc9d357f8'
down_revision: Union[str, None] = 'b57e0e969ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('url', sa.String(length=256), nullable=False), schema='access')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'url', schema='access')
    # ### end Alembic commands ###
