"""Add field action on audit

Revision ID: 87826ec858af
Revises: df079276fc33
Create Date: 2025-04-28 21:41:03.721074

"""

import sqlalchemy as sa
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "87826ec858af"
down_revision: Union[str, None] = "df079276fc33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("drop table if exists audit.audit_log")
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("target_data", sa.JSON(), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="audit",
    )
    op.create_index(
        op.f("ix_audit_audit_log_action"), "audit_log", ["action"], unique=False, schema="audit"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_audit_log_action"), table_name="audit_log", schema="audit")
    op.drop_table("audit_log", schema="audit")
    # ### end Alembic commands ###
