"""Remove column cpnj from company

Revision ID: 8e3f505ed049
Revises: 90c82e943507
Create Date: 2025-05-04 03:16:33.778178

"""
import sqlalchemy as sa
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8e3f505ed049'
down_revision: Union[str, None] = '90c82e943507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_cnpj_key', 'company', type_='unique')
    op.drop_column('company', 'cnpj')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('cnpj', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_unique_constraint('company_cnpj_key', 'company', ['cnpj'])
    # ### end Alembic commands ###
