"""Login Audit

Revision ID: bc1e891ac6dd
Revises: 6b6a1934df47
Create Date: 2025-05-07 01:07:06.749828

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.orm import Session
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bc1e891ac6dd"
down_revision: Union[str, None] = "6b6a1934df47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    session: Session = Session(bind=op.get_bind())
    session.commit()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "last_used_password",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("password", sa.String(length=64), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["login.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "password"),
    )
    op.add_column(
        "resource", sa.Column("url", sa.String(length=256), nullable=False), schema="access"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resource", "url", schema="access")
    op.drop_table("last_used_password")
    # ### end Alembic commands ###
